apiVersion: v1
kind: Service
metadata:
  name: quote-server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: quote-server
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      nodePort: {{ .Values.server.service.nodePort }}
